name: pos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  esc_pos_utils_plus: ^2.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  print_bluetooth_thermal: ^1.1.6

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
